from google import genai
from agents.llm_client import generate_with_fallback
from dotenv import load_dotenv

load_dotenv()


def humanize_response(situation, context_data=None):
    """
    Generate a natural, human-sounding AiDa response for a given situation.

    Args:
        situation: A short description of what happened (e.g. "workout_completed").
        context_data: Optional dict with relevant facts to include in the response.

    Returns:
        A natural language string generated by Gemini.
    """

    context_block = ""
    if context_data:
        context_block = "\n".join(
            f"- {key}: {value}" for key, value in context_data.items()
        )

    prompt = f"""
You are AiDa, a personal fitness and nutrition AI coach.

Your personality:
- Supportive but realistic
- Action-oriented
- Concise (2-3 sentences max)
- Warm and human, like a real coach talking to their client
- Never use emojis
- Never use excessive hype or generic motivational quotes
- Never use bullet points or markdown formatting in your response

Situation: {situation}

{f"Context:{chr(10)}{context_block}" if context_block else ""}

Write a short, natural response that AiDa would say in this situation.
Respond with ONLY the message text, nothing else.
"""

    client = genai.Client()

    response = generate_with_fallback(
        model="gemma-4-26b-a4b-it",
        contents=prompt,
    )

    return response.text.strip()
